### ISSUE TITLE
some data missing in responce

### ISSUE THREAD

**Issue by mzeeshan88** [FelixPrime/AliExpress#3]
Hi 

first of all thanks for your share .. we are hitting the API and we get data in responce but some of arguments are missing like i.e. COLOR is missing of an shoe item .. 

can you help me out on this and reply me as soon as you can??

Kind Regards

**Comment by FelixPrime** [comment]
Hi

You can read the documentation there: 
http://portals.aliexpress.com/help/help_center_API.html
But, I did not see in it the argument like "color" or "item properties".
You can add color to the keywords (search query). You'll get a list of 
products with the same color. eg,
Search query: "shoes red".

I will be glad if it can help you

30.03.2016 13:21, mzeeshan88 пишет:
