### ISSUE TITLE
Does Aliexpress Provide dotnet c# sdk ?

### ISSUE THREAD

**Issue by aman-saggu-git** [FelixPrime/AliExpress#5]
I need to integrate Ali express in C# dot net so i want to know whether Ali express provide any Rest API for that

**Comment by FelixPrime** [comment]
Read the documentation https://portals.aliexpress.com/help/help_center_API.html?spm=a2g01.8078014.0.5.P6v0Wv

**Comment by aman-saggu-git** [comment]
Yes i have seen that link and applied for developer account 1day ago . But i have read somewhere that after developer account approval We need to apply for API then they will take 5 days for approval. 

why they take some of time to make us able to use their API
