### ISSUE TITLE
Api Keys ??

### ISSUE THREAD

**Issue by michaelsomerville** [FelixPrime/AliExpress#8]
Where would you get these ?

**Comment by FelixPrime** [comment]
Hi.
You need to register on https://partner.aliexpress.com/ and Sign In.
Next. Go to AdCenter -> API Setting and press Apply Now.
You will be given the key in 5-10 days.

**Comment by michaelsomerville** [comment]
Awesome, got it all ..  what are you classifying define("APP_SECRET", "********"); ??
---
API KEY: xxxxx
Call frequency: 100000
Digital signature: xxxxxxxxx
---

Which one would be the secret, the signature ?

**Comment by FelixPrime** [comment]
define("APP_KEY", "API_KEY");
define("APP_SECRET", "DIGITAL_SIGNATURE");
