### ISSUE TITLE
flash deals

### ISSUE THREAD

**Issue by ghost** [FelixPrime/AliExpress#9]
how can i use this to get the flash deals from aliexpress??

**Comment by FelixPrime** [comment]
aorry, but the api does not contain a "flash deals" request. maybe in the future it will appear

**Comment by orlandoabreu221** [comment]
Thank you for your response,but do you have an url with rss feeds in XML
for the products or deals?just like amazon has
http://rssfeeds.s3.amazonaws.com/goldbox ,thanks and have a great day

Orlandoao's Development
http://www.orlandoao.com
